/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriviaRouteImport } from './routes/trivia'
import { Route as RequestCardRouteImport } from './routes/request-card'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GasRequestsRouteImport } from './routes/gas-requests'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CheckInsRouteImport } from './routes/check-ins'
import { Route as IndexRouteImport } from './routes/index'

const TriviaRoute = TriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCardRoute = RequestCardRouteImport.update({
  id: '/request-card',
  path: '/request-card',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRequestsRoute = GasRequestsRouteImport.update({
  id: '/gas-requests',
  path: '/gas-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInsRoute = CheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-ins': typeof CheckInsRoute
  '/checkin': typeof CheckinRoute
  '/gas-requests': typeof GasRequestsRoute
  '/home': typeof HomeRoute
  '/request-card': typeof RequestCardRoute
  '/trivia': typeof TriviaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-ins': typeof CheckInsRoute
  '/checkin': typeof CheckinRoute
  '/gas-requests': typeof GasRequestsRoute
  '/home': typeof HomeRoute
  '/request-card': typeof RequestCardRoute
  '/trivia': typeof TriviaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-ins': typeof CheckInsRoute
  '/checkin': typeof CheckinRoute
  '/gas-requests': typeof GasRequestsRoute
  '/home': typeof HomeRoute
  '/request-card': typeof RequestCardRoute
  '/trivia': typeof TriviaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-ins'
    | '/checkin'
    | '/gas-requests'
    | '/home'
    | '/request-card'
    | '/trivia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-ins'
    | '/checkin'
    | '/gas-requests'
    | '/home'
    | '/request-card'
    | '/trivia'
  id:
    | '__root__'
    | '/'
    | '/check-ins'
    | '/checkin'
    | '/gas-requests'
    | '/home'
    | '/request-card'
    | '/trivia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInsRoute: typeof CheckInsRoute
  CheckinRoute: typeof CheckinRoute
  GasRequestsRoute: typeof GasRequestsRoute
  HomeRoute: typeof HomeRoute
  RequestCardRoute: typeof RequestCardRoute
  TriviaRoute: typeof TriviaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trivia': {
      id: '/trivia'
      path: '/trivia'
      fullPath: '/trivia'
      preLoaderRoute: typeof TriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-card': {
      id: '/request-card'
      path: '/request-card'
      fullPath: '/request-card'
      preLoaderRoute: typeof RequestCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas-requests': {
      id: '/gas-requests'
      path: '/gas-requests'
      fullPath: '/gas-requests'
      preLoaderRoute: typeof GasRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-ins': {
      id: '/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof CheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInsRoute: CheckInsRoute,
  CheckinRoute: CheckinRoute,
  GasRequestsRoute: GasRequestsRoute,
  HomeRoute: HomeRoute,
  RequestCardRoute: RequestCardRoute,
  TriviaRoute: TriviaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
